# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MCMC_full <- function(n_iter, n_save, theta_t, y_t, ind_zero, beta_t, mu_t, Pi_t, ind_stat_cell, phi_t, n_cell, sigma_sq_t, clas_cell_t, lambda0_t, lambda1_t, S_t, S_vec_t, xi_vec_t, xi_prime_t, scale_factor_est, alpha_t, nu_t, gam_t, eta_mu, tau_sq_mu, eta_beta, tau_sq_beta, G, total_cell_num, L, K, m, tau_theta, radius, lam0_0, lam1_0, Sigma2_lam0, Sigma2_lam1, sd_lambda0, sd_lambda1, a_xi, b_xi, iter_save = FALSE, n_threads = 1L, iter_print = 1000L, class_print = FALSE) {
    .Call(`_SCSC_MCMC_full`, n_iter, n_save, theta_t, y_t, ind_zero, beta_t, mu_t, Pi_t, ind_stat_cell, phi_t, n_cell, sigma_sq_t, clas_cell_t, lambda0_t, lambda1_t, S_t, S_vec_t, xi_vec_t, xi_prime_t, scale_factor_est, alpha_t, nu_t, gam_t, eta_mu, tau_sq_mu, eta_beta, tau_sq_beta, G, total_cell_num, L, K, m, tau_theta, radius, lam0_0, lam1_0, Sigma2_lam0, Sigma2_lam1, sd_lambda0, sd_lambda1, a_xi, b_xi, iter_save, n_threads, iter_print, class_print)
}

update_mu_R <- function(theta_t, beta_t, sigma_sq_t, clas_cell_t, S_vec_t, K, G, eta_mu, tau_sq_mu) {
    .Call(`_SCSC_update_mu_R`, theta_t, beta_t, sigma_sq_t, clas_cell_t, S_vec_t, K, G, eta_mu, tau_sq_mu)
}

update_Pi_R <- function(clas_cell_t, S_vec_t, xi_vec_t, gam, L, K) {
    .Call(`_SCSC_update_Pi_R`, clas_cell_t, S_vec_t, xi_vec_t, gam, L, K)
}

